### ISSUE TITLE
Why compress /data/ to bzip?

### ISSUE THREAD

**Issue by NoNamePro0** [ard-data/2020-rki-archive#1]
Hello 👋

i think it's a stupid idea, to compress the data files to a bzip.

Git is not a tool for managing binarys, like zips. It will be used for text files and codes. So just for the JSON and CSV files.
If you want to reduce storage, this way is not suggested.

Your filename for the `bin` folder can be confusing. `bin` is an abbreviation for binarys, but the source code is not a binary but normal JavaScript and bash files.

Files in `/bin` from the UNIX file system are compiled binary.

I hope I could improve something. ✨

**Comment by MichaelKreil** [comment]
> compress the data files to a bzip.

I don't want to manage file histories or change or diff or merge binaries, I just want to archive them. So no, GitHub is a good solution.

What are the alternatives?

- Saving the uncompressed data would (currently) require 16 GB, exceeding the maximum repo size of 1 GB by 1500%. Also, it would be a completely inefficient use of storage space and bandwidth if you can easily compress the data by a factor of 70:1 instead!

- Of course, I could use some sort of cloud storage, but since the compressed data is only 250 MB in size, and the code should be nearby, GitHub is a very good solution.

BTW: you can process compressed JSON archives quite efficiently with e.g. `bzip2 -dkc *.json.bz2 | jq '.'`

> Your filename for the bin folder can be confusing…

In C you have your code in `src` and the compiled binaries in `bin`. But in NodeJS, the source code and the executable version are the same file. So where should they be stored? Well, since the default use case is to execute them, you should put them in `bin`. And that's fine, because text files are binary too.
Just imagine JavaScript is like C, but the executable files are human readable.

You can also have a look at this: https://github.com/standard/standard

But maybe this will help. The files now have a hashbang and execute permission: 116e443d35c5c5130ff6879d587da25e42c4c207

Thanks for your feedback.
Michael
