### ISSUE TITLE
All data gone?

### ISSUE THREAD

**Issue by outa** [ard-data/2020-rki-archive#3]
Hi,

it seems like all the data was removed from the archive. Is it gone for good? If yes, do you maybe know any other similar archive like this, where I can find daily versions of the RKI CSV file?

**Comment by MichaelKreil** [comment]
No. Because of the file size the data has moved into a cloud bucket:
https://github.com/ard-data/2020-rki-archive#wo-sind-die-daten-zu-finden

You can find the raw data here: https://storage.googleapis.com/brdata-public-data/rki-corona-archiv/0_archived/index.html
Parsed data is here: https://storage.googleapis.com/brdata-public-data/rki-corona-archiv/2_parsed/index.html

**Comment by MichaelKreil** [comment]
Sorry, this was an emergency fix as the GitHub repo has exceeded the 1GB limit.
Is cloud storage viable for you? Or do you need something else?

**Comment by outa** [comment]
Yes, it works fine. Thanks a lot :)
